#!/bin/sh

export JAVA_HOME=`/usr/libexec/java_home -v17`
SCRIPT_DIR=$(dirname "$(readlink -f "$0")")

java -jar $SCRIPT_DIR/target/jarnalyze.jar -exclude "/module-info.class|/META-INF/.*|.*\.html|.*\.txt|/NOTICE|/LICENSE" $*
